server:
  port: ${PORT:8085}
spring:
  application:
    name: gateway_module
#  cloud:
#    consul:
#      config:
#        enabled: false
#      host: ${CONSUL_HOST:localhost}
#      port: ${CONSUL_PORT:8500}
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 3000
#        readTimeout: 3000
#        loggerLevel: basic
